# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robotics.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'robotics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erobotics.proto\x12\x08robotics\"\x8c\x01\n\x12ObservationRequest\x12\x17\n\x0ftop_view_camera\x18\x01 \x01(\x0c\x12\x18\n\x10side_view_camera\x18\x02 \x01(\x0c\x12\x13\n\x0brobot_state\x18\x03 \x03(\x02\x12\x18\n\x10task_instruction\x18\x04 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\"]\n\x0e\x41\x63tionResponse\x12\x0f\n\x07\x61\x63tions\x18\x01 \x03(\x02\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x12\n\nlatency_ms\x18\x03 \x01(\x05\x12\x15\n\rerror_message\x18\x04 \x01(\t\"\x0f\n\rHealthRequest\"I\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x03 \x01(\x03\x32\x9b\x01\n\x0eSmolVLAService\x12G\n\rPredictAction\x12\x1c.robotics.ObservationRequest\x1a\x18.robotics.ActionResponse\x12@\n\x0bHealthCheck\x12\x17.robotics.HealthRequest\x1a\x18.robotics.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robotics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBSERVATIONREQUEST']._serialized_start=29
  _globals['_OBSERVATIONREQUEST']._serialized_end=169
  _globals['_ACTIONRESPONSE']._serialized_start=171
  _globals['_ACTIONRESPONSE']._serialized_end=264
  _globals['_HEALTHREQUEST']._serialized_start=266
  _globals['_HEALTHREQUEST']._serialized_end=281
  _globals['_HEALTHRESPONSE']._serialized_start=283
  _globals['_HEALTHRESPONSE']._serialized_end=356
  _globals['_SMOLVLASERVICE']._serialized_start=359
  _globals['_SMOLVLASERVICE']._serialized_end=514
# @@protoc_insertion_point(module_scope)
